export const HOBBY_CATEGORIES = {
  Technology: [
    "Web Development",
    "Mobile App Development",
    "Data Science",
    "Machine Learning",
    "Cybersecurity",
    "Cloud Computing",
    "DevOps",
    "Blockchain",
    "IoT",
    "Game Development",
  ],
  Programming: [
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "Rust",
    "Go",
    "TypeScript",
    "Swift",
    "Kotlin",
    "Ruby",
  ],
  "Artificial Intelligence": [
    "Natural Language Processing",
    "Computer Vision",
    "Deep Learning",
    "Neural Networks",
    "AI Ethics",
    "Prompt Engineering",
    "Robotics",
    "Data Mining",
    "Predictive Analytics",
    "AI Research",
  ],
  Electronics: [
    "Arduino",
    "Raspberry Pi",
    "Circuit Design",
    "3D Printing",
    "Home Automation",
    "Drone Building",
    "Robotics",
    "Soldering",
    "Electronics Repair",
    "Smart Home",
  ],
  Photography: [
    "Portrait Photography",
    "Landscape Photography",
    "Street Photography",
    "Wildlife Photography",
    "Macro Photography",
    "Astrophotography",
    "Drone Photography",
    "Film Photography",
    "Photo Editing",
    "Videography",
  ],
  Videography: [
    "Video Editing",
    "Filmmaking",
    "Content Creation",
    "Animation",
    "Motion Graphics",
    "Screenwriting",
    "Directing",
    "Cinematography",
    "Sound Design",
    "Video Production",
  ],
  Fitness: [
    "Weightlifting",
    "Running",
    "Yoga",
    "CrossFit",
    "Calisthenics",
    "Pilates",
    "Swimming",
    "Cycling",
    "HIIT",
    "Martial Arts",
  ],
  Sports: [
    "Basketball",
    "Soccer",
    "Tennis",
    "Golf",
    "Baseball",
    "Football",
    "Hockey",
    "Volleyball",
    "Badminton",
    "Table Tennis",
  ],
  "Outdoor Activities": [
    "Hiking",
    "Camping",
    "Backpacking",
    "Rock Climbing",
    "Kayaking",
    "Fishing",
    "Hunting",
    "Surfing",
    "Skiing",
    "Snowboarding",
  ],
  Travel: [
    "Backpacking Travel",
    "Road Trips",
    "Cultural Tourism",
    "Adventure Travel",
    "Eco Tourism",
    "Solo Travel",
    "Luxury Travel",
    "Cruise Travel",
    "Historical Sites",
    "Local Exploration",
  ],
  Food: [
    "Cooking",
    "Baking",
    "Grilling",
    "Food Photography",
    "Recipe Development",
    "Food Critique",
    "Wine Tasting",
    "Coffee Brewing",
    "Mixology",
    "Fermentation",
  ],
  Art: [
    "Painting",
    "Drawing",
    "Sculpting",
    "Digital Art",
    "Graffiti",
    "Calligraphy",
    "Printmaking",
    "Collage",
    "Art History",
    "Museum Visiting",
  ],
  Design: [
    "Graphic Design",
    "UI/UX Design",
    "Fashion Design",
    "Interior Design",
    "Industrial Design",
    "Product Design",
    "Logo Design",
    "Typography",
    "Brand Design",
    "Web Design",
  ],
  Music: [
    "Guitar",
    "Piano",
    "Drums",
    "Violin",
    "Singing",
    "Music Production",
    "DJing",
    "Songwriting",
    "Music Theory",
    "Audio Engineering",
  ],
  Reading: [
    "Fiction",
    "Non-Fiction",
    "Science Fiction",
    "Fantasy",
    "Biographies",
    "Self-Help",
    "Poetry",
    "Academic Reading",
    "Comic Books",
    "Audiobooks",
  ],
  Writing: [
    "Creative Writing",
    "Journaling",
    "Blogging",
    "Copywriting",
    "Screenwriting",
    "Poetry",
    "Technical Writing",
    "Ghostwriting",
    "Content Writing",
    "Journalism",
  ],
  Science: [
    "Astronomy",
    "Biology",
    "Chemistry",
    "Physics",
    "Psychology",
    "Neuroscience",
    "Environmental Science",
    "Geology",
    "Botany",
    "Zoology",
  ],
  Business: [
    "Entrepreneurship",
    "Marketing",
    "Sales",
    "Finance",
    "Investing",
    "Accounting",
    "Consulting",
    "Management",
    "E-Commerce",
    "Real Estate",
  ],
  Volunteering: [
    "Community Service",
    "Animal Welfare",
    "Environmental Conservation",
    "Education Support",
    "Healthcare Volunteering",
    "Disaster Relief",
    "Mentoring",
    "Charity Work",
    "Social Justice",
    "Elder Care",
  ],
  Education: [
    "Online Learning",
    "Language Learning",
    "Skill Development",
    "Academic Research",
    "Teaching",
    "Tutoring",
    "Curriculum Development",
    "Educational Technology",
    "Study Skills",
    "Professional Development",
  ],
  Gaming: [
    "PC Gaming",
    "Console Gaming",
    "Mobile Gaming",
    "Tabletop Games",
    "RPGs",
    "FPS Games",
    "Strategy Games",
    "Game Modding",
    "Speedrunning",
    "Esports",
  ],
  "Content Creation": [
    "YouTube",
    "TikTok",
    "Instagram",
    "Podcasting",
    "Streaming",
    "Blogging",
    "Newsletter Writing",
    "Social Media Management",
    "Influencer Marketing",
    "Community Building",
  ],
  "DIY & Maker Projects": [
    "Woodworking",
    "Metalworking",
    "Jewelry Making",
    "Knitting",
    "Crochet",
    "Sewing",
    "Embroidery",
    "Leatherworking",
    "Pottery",
    "Glassblowing",
  ],
  "Social Activities": [
    "Networking",
    "Public Speaking",
    "Event Planning",
    "Club Organization",
    "Team Building",
    "Leadership",
    "Negotiation",
    "Conflict Resolution",
    "Mentoring",
    "Coaching",
  ],
} as const;

export const DEFAULT_HOBBIES = Object.values(HOBBY_CATEGORIES).flat();

export const DEFAULT_BADGES = [
  "Food Explorer",
  "Tech Explorer",
  "Photographer",
  "Nature Hunter",
  "Fitness Warrior",
];

export const LEVEL_THRESHOLDS = [
  { level: 1, title: "Beginner", xp: 0 },
  { level: 2, title: "Explorer", xp: 100 },
  { level: 3, title: "Adventurer", xp: 300 },
  { level: 4, title: "Hero", xp: 700 },
  { level: 5, title: "Legend", xp: 1500 },
];

export const QUEST_STATUSES = [
  "generated",
  "accepted",
  "rejected",
  "pending_approval",
  "completed",
  "abandoned",
] as const;

export const NOTIFICATION_TYPES = [
  "friend_request",
  "friend_accepted",
  "like",
  "approval",
  "level_up",
] as const;
